x-server-config: &server-config
    PORT: 4112
    AWS_REGION: "eu-west-1"
    AWS_DYNAMO_ENDPOINT: "http://dynamodb:8000"
    AWS_ACCESS_KEY: dummyAccessKeyId
    AWS_SECRET_KEY: dummySecretAccessKey

services:
    server:
        container_name: bits-server
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - /node_modules
            - .:/app
        ports:
            - 4112:4112
        environment:
            <<: *server-config
        command: npm run dev

    dynamodb:
        image: amazon/dynamodb-local
        container_name: bits-dynamodb
        ports:
            - 8001:8000
