x-server-config: &server-config
    PORT: 4112
    AWS_REGION: eu-west-1
    AWS_DYNAMO_ENDPOINT: http://dynamodb:8000
    AWS_ACCESS_KEY: dummyAccessKeyId
    AWS_SECRET_KEY: dummySecretAccessKey
    AWS_ENDPOINT_URL: http://localstack:4566 # this is for localstack

services:
    server:
        container_name: bits-server
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - /node_modules
            - .:/app
        ports:
            - 4112:4112
        environment:
            <<: *server-config
        command: npm run dev

    dynamodb:
        image: amazon/dynamodb-local
        container_name: bits-dynamodb
        ports:
            - 8001:8000

    localstack:
        image: localstack/localstack
        ports:
            - "4566-4599:4566-4599"
            - "8080:8080"
        environment:
            SERVICES: dynamodb,lambda,apigateway,ssm,cloudformation,iam
            DEFAULT_REGION: eu-west-1
            DEBUG: 1
